name: CI
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: "16"
          distrubition: adopt
          cache: maven
      - name: Run with Maven
        run: mvn -B pacakge --file pom.xml